"""Merge the per-worker render manifests and emit the per-seed outcome report.

Verifies every referenced MP4 is present and playable (frame count > 0) so the
report cannot claim a video that was not actually produced.

  uv run python scripts/demo/merge_manifests.py \
      --manifests artifacts/demo/manifests --videos artifacts/demo/videos \
      --out artifacts/demo/REPORT.md --json artifacts/demo/summary.json
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import runs as run_registry  # noqa: E402

RUN_ORDER = ["table_setting", "plate", "mug", "bottle", "drawer", "drawer_fork",
             "attempt_spoon_place", "attempt_bottle_place"]


def probe_frames(path: Path) -> int:
    """Decoded frame count, or -1 when ffprobe cannot read the file."""
    try:
        out = subprocess.run(
            ["ffprobe", "-v", "error", "-count_frames", "-select_streams", "v:0",
             "-show_entries", "stream=nb_read_frames", "-of", "csv=p=0", str(path)],
            capture_output=True, text=True, timeout=120,
        )
        return int(out.stdout.strip() or -1)
    except Exception:  # noqa: BLE001
        return -1


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--manifests", type=Path, default=Path("artifacts/demo/manifests"))
    ap.add_argument("--videos", type=Path, default=Path("artifacts/demo/videos"))
    ap.add_argument("--out", type=Path, default=Path("artifacts/demo/REPORT.md"))
    ap.add_argument("--json", type=Path, default=Path("artifacts/demo/summary.json"))
    ap.add_argument("--skip-verify", action="store_true")
    args = ap.parse_args()

    merged: dict[str, dict[int, dict]] = {}
    for mf in sorted(args.manifests.glob("*.json")):
        data = json.loads(mf.read_text(encoding="utf-8"))
        for run, seeds in data.get("runs", {}).items():
            for seed_str, rec in seeds.items():
                merged.setdefault(run, {})[int(seed_str)] = rec

    # Verify each referenced file exists and decodes.
    if not args.skip_verify:
        for run, seeds in merged.items():
            for seed, rec in seeds.items():
                p = Path(rec["file"])
                if not p.is_file():
                    rec["verified"] = False
                    rec["verify_note"] = "file missing"
                    continue
                n = probe_frames(p)
                rec["verified"] = n > 0
                rec["decoded_frames"] = n
                if n <= 0:
                    rec["verify_note"] = "ffprobe could not decode any frames"

    runs = [r for r in RUN_ORDER if r in merged] + [r for r in sorted(merged) if r not in RUN_ORDER]

    lines: list[str] = []
    lines.append("# Per-seed demonstration outcomes\n")
    lines.append("Generated by `scripts/demo/merge_manifests.py` from the render "
                 "manifests. `success` is the run's own verdict (every step "
                 "reached `success`); a red-marked video is a run that did not.\n")
    lines.append("## Summary\n")
    lines.append("| run | seeds rendered | success | failed | expected-failure run |")
    lines.append("| --- | --- | --- | --- | --- |")
    for run in runs:
        seeds = merged[run]
        ok = sum(1 for r in seeds.values() if r["success"])
        bad = len(seeds) - ok
        exp = "yes" if run in run_registry.EXPECTED_FAILURE else "no"
        lines.append(f"| `{run}` | {len(seeds)}/10 | {ok} | {bad} | {exp} |")

    lines.append("\n## Per-seed detail\n")
    lines.append("| run | seed | outcome | failed step | cause | frames | sim s | "
                 "OV p50 ms | OV p95 ms | OV inf | video |")
    lines.append("| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |")
    for run in runs:
        for seed in sorted(merged[run]):
            r = merged[run][seed]
            verdict = "SUCCESS" if r["success"] else "**FAILED**"
            if r.get("expected_failure") and not r["success"]:
                verdict = "**FAILED (expected)**"
            fs = r.get("failed_step", -1)
            step_desc = "-"
            if fs is not None and fs >= 0 and fs < len(r["steps"]):
                st = r["steps"][fs]
                step_desc = f"{st['skill']} {st['object'] or ''}".strip()
            ov = r.get("openvino", {})
            p50 = f"{ov['p50_ms']:.1f}" if (ov.get("available") and ov.get("p50_ms")) else "-"
            p95 = f"{ov['p95_ms']:.1f}" if (ov.get("available") and ov.get("p95_ms")) else "-"
            inf = ov.get("inferences", 0) if ov.get("available") else "-"
            name = Path(r["file"]).name
            vnote = "" if r.get("verified", True) else " (UNVERIFIED)"
            lines.append(
                f"| `{run}` | {seed} | {verdict} | {step_desc} | {r.get('failure') or '-'} "
                f"| {r.get('frames', '-')} | {r.get('sim_time_s', '-')} | {p50} | {p95} "
                f"| {inf} | `{run}/{name}`{vnote} |"
            )

    total = sum(len(v) for v in merged.values())
    verified = sum(1 for v in merged.values() for r in v.values() if r.get("verified", True))
    lines.append(f"\n**{total} videos; {verified} verified present and decodable.**\n")

    lines.append("\n## Notes\n")
    lines.append("- OpenVINO p50/p95 are measured **in-loop during that episode**, "
                 "with several render workers competing for the CPU, so they are "
                 "higher than the idle-host figures in `bench/`. They are "
                 "within-episode measurements, not a clean benchmark.")
    lines.append("- The two `attempt_*` runs are expected to fail on every seed; they "
                 "are rendered so the limitation is visible rather than only asserted.")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    args.json.write_text(json.dumps(
        {run: {str(s): r for s, r in seeds.items()} for run, seeds in merged.items()},
        indent=2), encoding="utf-8")

    for run in runs:
        ok = sum(1 for r in merged[run].values() if r["success"])
        print(f"{run:22s} {ok}/{len(merged[run])} success")
    print(f"\nwrote {args.out} and {args.json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
